/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

#include "../standardHeaders.h"

char findTheDifference(char * s, char * t){   
    // since there is only one return character, assign it to a variable of type char
    char ch = 0;
    
    // XOR this return char 'ch' with all characters from first string
    // the remaining will be difference of all the characters
    for(int i=0; i<strlen(s); i++){
        ch ^= s[i];
    }
    
    // XOR this return char 'ch' with all characters from next string
    // the remaining will be difference of all the characters w.r.t.
    // characters from first string
    for(int i=0; i<strlen(t); i++){        
        ch ^= t[i];
    }    
    
    // return the remaining character
    return ch;
}


int main(void){

    char strs[][8] = {"ab", "abc", "abcd", "abcde", "abcd", "dcbaz"};
    for(int i=0; i<7; i=i+2){
        printf("Str 1: %s, Str 2: %s, diff element: %c\n",strs[i],strs[i+1],findTheDifference(strs[i],strs[i+1]));
    }
    return 0;
}
